# Generated by Django 3.1.3 on 2020-12-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='itemsjson',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
