# Generated by Django 3.1.3 on 2020-12-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders_itemsjson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
