# Generated by Django 3.1.3 on 2021-01-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210102_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cur_status',
        ),
    ]
